jobs:
  build:
    env:
      python-version: 3.8
      
      # Add any other environment variables here if needed
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python interest.py
