name: Python Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install -r interestcalc/requirements.txt -r interestcalc/requirements-actions.txt
    - name: Run Python script
      run: python3 interest.py
